#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.

app_path=$0

while [ -h "$app_path" ]; do
  ls=$(ls -ld "$app_path")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  case $link in
    /*) app_path=$link ;;
    *) app_path=$(dirname "$app_path")/$link ;;
  esac
done

APP_HOME=$(cd "${app_path%/*}" >/dev/null 2>&1 && pwd -P) || exit 1

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ]; then
  JAVACMD=$JAVA_HOME/bin/java
else
  JAVACMD=java
fi

if [ ! -x "$JAVACMD" ] && ! command -v "$JAVACMD" >/dev/null 2>&1; then
  echo "ERROR: JAVA_HOME is not set and no 'java' command could be found." >&2
  exit 1
fi

DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'

set -- "$@"

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  "-Dorg.gradle.appname=$(basename "$0")" \
  -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
